version: "3"
services:
  IrrigationEngine:
    image: node:10.16.0
    command: npm start
    working_dir: /app
    environment:
      - ORION_URL=http://orion:1026 
    volumes:
      - /opt/fiware4africa/IrrigationEngine:/app
    deploy:
      replicas: 1
    ports:
      - "8082:8080"
    networks:
      fiware_orion:
      monitoring:
          aliases:
            - irrigation
      digitalfarmapi:
          aliases:
            - simulationengine

  SimulationEngine:
    image: node:10.16.0
    command: npm start
    working_dir: /app
    environment:
      - ORION_URL=http://orion:1026 
    volumes:
      - /opt/fiware4africa/SimulationEngine:/app
    deploy:
      replicas: 1
    ports:
      - "8081:8080"
    networks:
      fiware_orion:
      monitoring:
          aliases:
            - simulation
      digitalfarmapi:
          aliases:
            - simulationengine
  MonitoringProxy:
    image: node:10.16.0
    command: npm start
    working_dir: /app
    environment:
      - PHYSICAL_URL=http://192.168.100.1:8080/api/status 
    volumes:
      - /opt/fiware4africa/MonitoringProxy:/app
    deploy:
      replicas: 1
    ports:
      - "8084:8080"
    networks:
      fiware_orion:
      fiware_comet:
      fiware_cygnus:
      digitalfarmapi:
        aliases:
          - monitoringengine

  farmdb:
    image: mongo
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=admin
    volumes:
       - /var/data/farmdb:/data/db
    deploy:
      replicas: 1
    networks:
      digitalfarmapi:
          aliases:
            - database
  digitalfarmapi:
    image: node:10.16.0
    command: npm start
    working_dir: /app
    environment:
      - ORION_URL=http://orion:1026 
    volumes:
      - /opt/fiware4africa/maquette-frontandroid:/app
    deploy:
      replicas: 1
    ports:
      - "8083:8080"
    networks:
      - fiware_orion
      - fiware_comet
      - fiware_cygnus
      - digitalfarmapi
  thecity:
    image: nginx
    volumes:
      - /opt/fiware4africa/TheCity/dist:/usr/share/nginx/html
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - digitalfarm
networks:
  monitoring:
  irrigation:
  digitalfarm:
  digitalfarmapi:
  fiware_orion:
    external: true
  fiware_comet:
    external: true
  fiware_cygnus:
    external: true